# -*- coding: utf-8 -*-
"""Stack Overflow Survey Analysis (Python Notebook).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SXiP2BvJynu37VIhDDIyesHCou-Q9G6z
"""

# ========================
# IMPORTS
# ========================
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

# ========================
# LOAD DATA (FIXED)
# ========================
df = pd.read_csv(
    'survey_results_public.csv',
    encoding='utf-8',
    on_bad_lines='skip',
    engine='python'
)

schema = pd.read_csv(
    'survey_results_schema.csv',
    encoding='utf-8',
    engine='python'
)

print("Data loaded successfully")
print(df.shape)
df.head()

from google.colab import drive
drive.mount('/content/drive')

# Task 1 — Total respondents
total_respondents = len(df)

print("Total respondents:", total_respondents)

"""**Conclusion:** A total of 40,191 respondents participated in the survey. This represents a sufficiently large dataset for analysis."""

# Task 2 — Full answers

questions = set(schema['qname'])
columns = set(df.columns)

valid_columns = list(questions.intersection(columns))

full_answers = df[valid_columns].dropna(how='any')

print("Respondents with full answers:", len(full_answers))

"""**Conclusion:** There are no respondents who answered all questions. This is likely due to the large number of questions and missing values in the dataset."""

# Task 3 — Work experience

work_exp = df['WorkExp'].dropna()

print("Mean:", work_exp.mean())
print("Median:", work_exp.median())
print("Mode:", work_exp.mode()[0])

"""**Conclusion:** The average work experience is about 13 years, while the median and most common value are 10 years. This indicates that most respondents have around 10 years of experience."""

# Task 4 — Remote work

df['RemoteWork'].value_counts()

remote_workers = df[df['RemoteWork'] == 'Remote'].copy()

print("Remote workers:", len(remote_workers))

"""**Conclusion:** 10,931 respondents work fully remotely. This shows a significant number of professionals prefer remote work."""

# Task 5 — Python %

python_users = df['LanguageHaveWorkedWith'].str.contains('Python', na=False)

python_percent = round(python_users.mean() * 100, 2)

print("Python users:", python_percent, "%")

"""**Conclusion:** Approximately 37.5% of respondents use Python. This confirms the high popularity of Python among developers."""

# Task 6 — Online learning

online_users = df['LearnCode'].str.contains('Online', case=False, na=False)

print("Users who learned online:", online_users.sum())

"""**Conclusion:** 28,352 respondents learned programming through online courses. This shows that online learning is one of the most popular ways to learn programming."""

# Task 7 — Salary analysis

# filter Python developers
python_dev = df[df['LanguageHaveWorkedWith'].str.contains('Python', na=False)]

# group data by country and calculate mean and median salary
salary_stats = python_dev.groupby('Country')['ConvertedCompYearly'].agg(['mean', 'median'])

# remove missing values
salary_stats = salary_stats.dropna()

# round values and sort by average salary
salary_stats = salary_stats.round(2).sort_values(by='mean', ascending=False)

salary_stats.head()

"""**Conclusion:** Salary levels for Python developers vary significantly across countries. In some countries, there is a large difference between average and median salaries, which may indicate uneven income distribution."""

# Task 8 — Education

salary_df = df[['ConvertedCompYearly', 'EdLevel']].dropna(subset=['ConvertedCompYearly'])

top5_education = salary_df.sort_values(by='ConvertedCompYearly', ascending=False).head(5)

top5_education

"""**Conclusion:** Among the highest-paid respondents, both bachelor's and master's degrees are common. This suggests that high income is possible with different levels of education."""

# Task 9 — Python by age

# create a copy of the DataFrame to avoid SettingWithCopyWarning
df_copy = df[['Age', 'LanguageHaveWorkedWith']].copy()

# create a column indicating Python usage
df_copy['UsesPython'] = df_copy['LanguageHaveWorkedWith'].str.contains('Python', na=False)

# group by age and calculate percentage of Python users
python_by_age = df_copy.groupby('Age')['UsesPython'].mean() * 100

# round values
python_by_age = python_by_age.round(2)

python_by_age

"""**Conclusion:** Python is most popular among younger respondents (18–24), where it is used by around 40% of developers. With increasing age, Python usage gradually decreases."""

# Задание 10 — индустрии топ-remote

# calculate 75th percentile of salary
threshold = df['ConvertedCompYearly'].quantile(0.75)

# filter: salary above threshold and remote workers
filtered = df[
    (df['ConvertedCompYearly'] > threshold) &
    (df['RemoteWork'] == 'Remote')
]

# remove missing values in industry column
filtered = filtered.dropna(subset=['Industry'])

# count most common industries
top_industries = filtered['Industry'].value_counts()

top_industries

"""**Conclusion:** Among highly paid remote workers, the most common industry is Software Development. Fintech and Healthcare also have a significant share. This indicates that the IT sector remains a leader in high-paying jobs."""

# ========================
# DATA VISUALIZATION
# ========================

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

# check which respondents use Python in the programming languages column
python_users = df['LanguageHaveWorkedWith'].str.contains('Python', na=False)

# calculate percentage of Python users
python_percent = round(python_users.mean() * 100, 2)

# calculate percentage of other users
other_percent = 100 - python_percent

# create bar chart to compare Python vs other languages
plt.figure()
plt.bar(['Python', 'Other Languages'], [python_percent, other_percent])

# add title and axis label
plt.title('Python Usage Among Developers')
plt.ylabel('Percentage (%)')

# display the chart
plt.show()

# filter respondents who use Python
python_dev = df[df['LanguageHaveWorkedWith'].str.contains('Python', na=False)]

# group data by country and calculate average salary
salary_stats = python_dev.groupby('Country')['ConvertedCompYearly'].mean()

# remove missing values and sort countries by salary
salary_stats = salary_stats.dropna().sort_values(ascending=False)

# select top 10 countries
top_countries = salary_stats.head(10)

# create horizontal bar chart for better readability
plt.figure(figsize=(10,6))
plt.barh(top_countries.index, top_countries.values)

# add title and axis labels
plt.title('Top 10 Countries by Average Salary (Python Developers)')
plt.xlabel('Average Salary (USD)')
plt.ylabel('Country')

# invert axis to show highest values on top
plt.gca().invert_yaxis()

# display the chart
plt.show()